config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about'
  get 'pages/contact'
  resources :posts, except: [:destroy] do
  get 'destroy', on: :member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  #Titel und Inhalt müssen vorhanden sein
  validates :titel, :content, :presence => true

  #Titel soll eine min. Länge von 5 Zeichen haben
  validates :titel, :length => { :minimum => 5 }

  #Titel soll einzigartig sein
  validates :titel, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  def create
    @post = Post.new (post_params)

    if @post.save
      redirect_to posts_path
    else
      render "new"
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes (post_params)    #wenn die Änderungen mit den Parameter übereinstimmen
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:titel, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">

    <a class="navbar-brand" <%= link_to "MY BLOG", posts_path %> </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Home", posts_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "About", pages_about_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Contact", pages_contact_path %></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/about-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>About Me</h1>
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/pages/contact.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/contact-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>Contact Me</h1>
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/posts/edit.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/post-sample-image.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Beitrag editieren</h1>
        </div>
      </div>
    </div>
  </div>
</header>


<!-- Schleife zur Fehlerprüfung -->
<% if @post.errors.any? %>
  <h2> Fehler:</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%=message%></li>
    <% end %>
  </ul>
<% end %>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <%= form_for @post do |f| %>
            <p>
              <%= f.label :titel %><br>
              <%= f.text_field :titel %>
            </p>

            <p>
              <%= f.label :content %><br>
              <%= f.text_area :content %>
            </p>

            <p>
              <%= f.submit "Editieren" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<hr>

app/views/posts/index.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @posts.each do |post| %>                                                <!-- Start der Schleife -->
        <div class="post-preview">
          <h2 class="post-title"><%= link_to post.titel, post %></h2>            <!-- Ausgabe (=) Titel + Verlinkung -->
          <h3 class="post-subtitle"><%= post.content %></h3>                     <!-- Ausgabe Inhalt -->
          <p><%= link_to "Editieren", edit_post_path(post)%> |
          <%= link_to "Löschen" ,post, :data => {:confirm => "Bist du sicher?"}, :method => :delete %></p>
        </div>
        <hr>
      <% end %>                                                                 <!-- Ende der Schleife-->
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
      <%= will_paginate @posts %>
    </div>
  </div>
</div>

<hr>


<p><%= link_to "Neuer Eintrag", new_post_path%></p>   <!--Verlinkung zum neuen Eintrag-->

app/views/posts/new.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Neuer Beitrag</h1>
        </div>
      </div>
    </div>
  </div>
</header>



<% if @post.errors.any? %>
  <h2> Fehler:</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%=message%></li>
    <% end %>
  </ul>
<% end %>
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <%= form_for @post do |f| %>
            <p>
              <%= f.label :titel %><br>
              <%= f.text_field :titel %>
            </p>
            <p>
              <%= f.label :content %><br>
              <%= f.text_area :content %>
            </p>

            <p>
              <%= f.submit "Speichern" %>
            </p>
          <% end %>
        </div>
    </div>
  </div>
</div>
<hr>

app/views/posts/show.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('../assets/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1><%= @post.titel %></h1>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <p><%= @post.content %></p>
          <small><%= @post.created_at %></small>
        </div>
        <hr>